name: fmiscup
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  pdfx: ^2.9.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.1.0
  webview_flutter: ^4.2.2
  flutter_pdfview: ^1.2.5
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  image: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  http: ^1.6.0
  url_launcher: ^6.1.5
  fluttertoast: ^8.2.12
  sqflite: ^2.4.2
  timezone: ^0.9.0
  connectivity_plus: ^6.0.5
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/

flutter_icons:
  android: false
  ios: true
  image_path: "assets/image/logo.png"
  remove_alpha_ios: true
